export const ADD_QUESTION = 'ADD_QUESTION';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
